# Generated by Django 5.0 on 2023-12-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.IntegerField(max_length=5),
        ),
    ]
