# Generated by Django 5.0 on 2023-12-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlite', '0005_book_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(default='', editable=False),
        ),
    ]
